#!/bin/sh
set -e
set -x

exec 2>&1

export APPLICATION_WEB_PROXY_BASE="${HISTORY_SERVER_WEB_PROXY_BASE}"
export SPARK_HISTORY_OPTS="-Dspark.history.ui.port=${HISTORY_SERVER_PORT} -Dspark.history.fs.logDirectory=${HISTORY_LOG_DIR} -Dspark.history.fs.cleaner.enabled=${HISTORY_CLEANER_ENABLED} -Dspark.history.fs.cleaner.interval=${HISTORY_CLEANER_INTERVAL} -Dspark.history.fs.cleaner.maxAge=${HISTORY_CLEANER_MAXAGE}"

if [ -n "${HISTORY_KRB_PRINCIPAL}" ]; then
    if [ -z "${HISTORY_KRB_KEYTAB}" ]; then
        echo "ERROR: If history-server.kerberos.principal is set, history-server.kerberos.keytab must also be set." 1>&2
        exit 1
    fi

    # write keytab
    KRB_KEYTAB_TMP_FILE=$(mktemp -t krb5-XXXXX.conf)
    chmod 400 "${KRB_KEYTAB_TMP_FILE}"
    echo "${HISTORY_KRB_KEYTAB}" | base64 -d > "${KRB_KEYTAB_TMP_FILE}"

    export SPARK_HISTORY_OPTS="${SPARK_HISTORY_OPTS} -Dspark.history.kerberos.enabled=true -Dspark.history.kerberos.principal=${HISTORY_KRB_PRINCIPAL} -Dspark.history.kerberos.keytab=${KRB_KEYTAB_TMP_FILE}"
fi

cd /opt/spark/dist
exec /opt/spark/dist/bin/spark-class org.apache.spark.deploy.history.HistoryServer
