#!/bin/sh
set -e
set -x

exec 2>&1
vars="s,<PORT>,${SPARK_PROXY_PORT},;s,<DISPATCHER_URL>,http://${HOST}:${DISPATCHER_PORT},;s,<DISPATCHER_UI_URL>,http://${HOST}:${DISPATCHER_UI_PORT},;s,<HISTORY_SERVER_URL>,http://${HOST}:${HISTORY_SERVER_PORT},"

sed "${vars}" /etc/nginx/conf.d/spark.conf.template >/etc/nginx/conf.d/spark.conf

# TODO(sur) remove, debug only
cat /etc/nginx/conf.d/spark.conf
env | sort

exec /usr/sbin/nginx -c /etc/nginx/nginx.conf

