{
 "title": "GPU",
 "description": "GPU metrics",
 "tags": [ "gpu" ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "mem_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gpu_mem_total" },
    {}
   ]
  },
  {
   "title": "mem_free",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gpu_mem_free" }
   ]
  },
  {
   "title": "mem_used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gpu_mem_used" },
    { "expr": "e" }
   ]
  },
  {
   "title": "mem_utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gpu_mem_utilization" }
   ]
  },
  {
   "title": "power_limit",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gpu_power_limit " }
   ]
  },
  {
   "title": "power_draw",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gpu_power_draw" },
    {}
   ]
  },
  {
   "title": "temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Degrees Celsius" }
   ],
   "targets": [
    { "expr": "gpu_temperature" }
   ]
  }
 ]
}