{
 "title": "Spark: Jobs Details",
 "time": { "from": "2018-05-17T18:14:06.744Z", "to": "2018-05-18T00:14:06.746Z" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Dispatcher 0 Offers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesos_master_framework_offers{framework_name=\"dispatcher-mixed-0\"}"
    }
   ]
  },
  {
   "title": "# Currently launched / waiting / retry jobs by dispatcher",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_mesos_cluster_driver_launched"
    }
   ]
  },
  {
   "title": "# Dispatchers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(spark_mesos_cluster_driver_launched)"
    }
   ]
  },
  {
   "title": "Job duration (min.) mean",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_mesos_cluster_driver_launch_to_finish_state_finished_mean / 60000"
    }
   ]
  },
  {
   "title": "offers_received",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "offers_received" }
   ]
  },
  {
   "title": "Median Submit to First Launch (stacked)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "spark_mesos_cluster_driver_submit_to_first_launch_p50",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Job launch time (sec) - driver start to all executors launched",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_mesos_cluster_executor_start_to_all_launched_mean / 1000"
    }
   ]
  },
  {
   "title": "Driver Launches by Dispatcher",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_mesos_cluster_driver_launched",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "# Currently launched / waiting / retry jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(spark_mesos_cluster_driver_launched)",
     "legendFormat": "launched"
    },
    {
     "expr": "sum(spark_mesos_cluster_driver_waiting)",
     "legendFormat": "waiting"
    },
    {
     "expr": "sum(spark_mesos_cluster_driver_retry)",
     "legendFormat": "retry"
    }
   ]
  },
  {
   "title": "Executor count by job",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_mesos_cluster_executor_count"
    }
   ]
  },
  {
   "title": "Median Submit to First Launch",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "spark_mesos_cluster_driver_submit_to_first_launch_p50",
     "legendFormat": "{{task_name}}"
    }
   ]
  }
 ]
}