{
 "title": "Spark: Summary",
 "description": "Spark Dispatcher and Driver Level Metrics with filtering by service",
 "tags": [ "spark" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "origin", "label": "Origin", "query": "label_values(spark_origin)" },
   {
    "name": "app_name",
    "label": "Application Name",
    "query": "label_values(spark_driver_jvm_heap_used{spark_origin =~ \"[[origin]]\" }, spark_app_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dispatchers",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      { "expr": "count(spark_jvm_total_max)" }
     ]
    },
    {
     "title": "Drivers (total)",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(spark_driver_jvm_heap_max)"
      }
     ]
    },
    {
     "title": "Executors (total)",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(spark_executor_jvm_heap_max)"
      }
     ]
    },
    {
     "title": "Drivers (client mode)",
     "type": "singlestat",
     "description": "This metric displays the number of drivers launched by spark-submit in client mode (bypassing Spark Mesos Dispatcher)",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(spark_driver_jvm_heap_max{spark_origin=\"spark-submit\"})"
      }
     ]
    },
    {
     "title": "Executors (client mode)",
     "type": "singlestat",
     "description": "This metric displays the number of executors launched by spark-submit in client mode (bypassing Spark Mesos Dispatcher)",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(spark_executor_jvm_heap_max{spark_origin=\"spark-submit\"})"
      }
     ]
    },
    {
     "title": "Spark Applications",
     "type": "singlestat",
     "description": "This metric displays the number of applications running in the cluster based on the application name value.",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count by (app_name) (spark_jvm_heap_max)"
      }
     ]
    },
    {
     "title": "Total CPUs Used",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(spark_mesos_resource_cores)",
       "legendFormat": "CPUs Used by Application"
      }
     ]
    },
    {
     "title": "Total GPUs Used",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "sum(spark_mesos_resource_gpus)", "legendFormat": "GPUs Used by Application" }
     ]
    }
   ]
  },
  {
   "title": "Dispatcher Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Drivers Running",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(spark_mesos_drivers_launched{DCOS_SERVICE_NAME=~\"[[origin]]\"})"
      }
     ]
    },
    {
     "title": "Drivers Waiting",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(spark_mesos_drivers_waiting{DCOS_SERVICE_NAME=~\"[[origin]]\"})"
      }
     ]
    },
    {
     "title": "Drivers Finished",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 10, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(spark_mesos_drivers_finished{DCOS_SERVICE_NAME=~\"[[origin]]\"})"
      }
     ]
    },
    {
     "title": "Drivers Retried",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 14, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(spark_mesos_drivers_retry{DCOS_SERVICE_NAME=~\"[[origin]]\"})"
      }
     ]
    },
    {
     "title": "Driver Exceptions (count)",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(spark_mesos_drivers_exception_count{DCOS_SERVICE_NAME=~\"[[origin]]\"})"
      }
     ]
    },
    {
     "title": "Drivers Submit to Finish Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "spark_mesos_drivers_submit_to_finish_mean_upper{DCOS_SERVICE_NAME=~\"[[origin]]\"}"
      }
     ]
    },
    {
     "title": "Drivers Submit to Launch Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "spark_mesos_drivers_submit_to_first_launch_mean_upper{DCOS_SERVICE_NAME=~\"[[origin]]\"}"
      }
     ]
    },
    {
     "title": "Drivers Launch to Finish Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "spark_mesos_drivers_launch_to_finish_mean_upper{DCOS_SERVICE_NAME=~\"[[origin]]\"}"
      }
     ]
    },
    {
     "title": "Drivers Submit to Exception Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "spark_mesos_drivers_submit_to_exception_mean_upper{DCOS_SERVICE_NAME=~\"[[origin]]\"}"
      }
     ]
    },
    {
     "title": "Drivers Submit to Finish Time (with states)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "spark_mesos_drivers_submit_to_finish_state_finished_mean_upper{DCOS_SERVICE_NAME=~\"[[origin]]\"}"
      },
      {
       "expr": "spark_mesos_drivers_submit_to_finish_state_failed_mean_upper{DCOS_SERVICE_NAME=~\"[[origin]]\"}"
      },
      {
       "expr": "spark_mesos_drivers_submit_to_finish_state_killed_mean_upper{DCOS_SERVICE_NAME=~\"[[origin]]\"}"
      },
      {
       "expr": "spark_mesos_drivers_submit_to_finish_state_lost_mean_upper{DCOS_SERVICE_NAME=~\"[[origin]]\"}"
      },
      {
       "expr": "spark_mesos_drivers_submit_to_finish_state_unknown_mean_upper{DCOS_SERVICE_NAME=~\"[[origin]]\"}"
      }
     ]
    },
    {
     "title": "Drivers Launch to Finish Time (with states)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "spark_mesos_drivers_launch_to_finish_state_finished_mean_upper{DCOS_SERVICE_NAME=~\"[[origin]]\"}"
      },
      {
       "expr": "spark_mesos_drivers_launch_to_finish_state_failed_mean_upper{DCOS_SERVICE_NAME=~\"[[origin]]\"}"
      },
      {
       "expr": "spark_mesos_drivers_launch_to_finish_state_killed_mean_upper{DCOS_SERVICE_NAME=~\"[[origin]]\"}"
      },
      {
       "expr": "spark_mesos_drivers_launch_to_finish_state_lost_mean_upper{DCOS_SERVICE_NAME=~\"[[origin]]\"}"
      },
      {
       "expr": "spark_mesos_drivers_launch_to_finish_state_unknown_mean_upper{DCOS_SERVICE_NAME=~\"[[origin]]\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Driver Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Executors Running",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(spark_mesos_executor_count{spark_origin=~\"[[origin]]\", spark_app_name=~\"[[app_name]]\"})"
      }
     ]
    },
    {
     "title": "Mesos Agents Used",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(spark_mesos_occupied_agents{spark_origin=~\"[[origin]]\"}) "
      }
     ]
    },
    {
     "title": "Blacklisted Agents",
     "type": "singlestat",
     "description": "Number of blacklisted agents (too many failures)",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(spark_mesos_blacklisted_agents{spark_origin=~\"[[origin]]\"})"
      }
     ]
    },
    {
     "title": "CPUs Used",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(spark_mesos_resource_cores{spark_origin=~\"[[origin]]\"}) by (app_name)",
       "legendFormat": "CPUs Used by Application"
      }
     ]
    },
    {
     "title": "GPUs Used",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(spark_mesos_resource_gpus{spark_origin=~\"[[origin]]\"}) by (app_name)",
       "legendFormat": "GPUs Used by Application"
      }
     ]
    },
    {
     "title": "CPUs per Task",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(spark_mesos_resource_mean_cores_per_task{spark_origin=~\"[[origin]]\"}) by (app_name)",
       "legendFormat": "GPUs Used by Application"
      }
     ]
    },
    {
     "title": "GPUs per Task",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(spark_mesos_resource_mean_gpus_per_task{spark_origin=~\"[[origin]]\"}) by (app_name)",
       "legendFormat": "GPUs Used by Application"
      }
     ]
    },
    {
     "title": "Driver Heap (max/used)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max(spark_driver_jvm_total_max{spark_origin=~\"[[origin]]\"}) by (app_name)",
       "legendFormat": "Heap max"
      },
      {
       "expr": "max(spark_driver_jvm_total_used{spark_origin=~\"[[origin]]\"}) by (app_name)",
       "legendFormat": "Heap used"
      }
     ]
    },
    {
     "title": "Executor Heap (max/used)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max(spark_executor_jvm_total_max{spark_origin=~\"[[origin]]\"}) by (app_name)",
       "legendFormat": "Heap max"
      },
      {
       "expr": "max(spark_executor_jvm_total_used{spark_origin=~\"[[origin]]\"}) by (app_name)",
       "legendFormat": "Heap used"
      }
     ]
    },
    {
     "title": "Mesos Task Status",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "sum(spark_mesos_mesos_state_task_running{spark_origin=~\"[[origin]]\", spark_app_name=~\"[[app_name]]\"})",
       "legendFormat": "dropped"
      },
      {
       "expr": "sum(spark_mesos_mesos_state_task_finished{spark_origin=~\"[[origin]]\", spark_app_name=~\"[[app_name]]\"})"
      },
      {
       "expr": "sum(spark_mesos_mesos_state_task_failed{spark_origin=~\"[[origin]]\", spark_app_name=~\"[[app_name]]\"})"
      },
      {
       "expr": "sum(spark_mesos_mesos_state_task_error{spark_origin=~\"[[origin]]\", spark_app_name=~\"[[app_name]]\"})"
      },
      {
       "expr": "sum(spark_mesos_mesos_state_task_killed{spark_origin=~\"[[origin]]\", spark_app_name=~\"[[app_name]]\"})"
      },
      {
       "expr": "sum(spark_mesos_mesos_state_task_lost{spark_origin=~\"[[origin]]\", spark_app_name=~\"[[app_name]]\"})"
      },
      {
       "expr": "sum(spark_mesos_mesos_state_task_dropped{spark_origin=~\"[[origin]]\", spark_app_name=~\"[[app_name]]\"})"
      },
      {
       "expr": "sum(spark_mesos_mesos_state_task_gone{spark_origin=~\"[[origin]]\", spark_app_name=~\"[[app_name]]\"})"
      },
      {
       "expr": "sum(spark_mesos_mesos_state_task_unreachable{spark_origin=~\"[[origin]]\", spark_app_name=~\"[[app_name]]\"})"
      },
      {
       "expr": "sum(spark_mesos_mesos_state_task_unknown{spark_origin=~\"[[origin]]\", spark_app_name=~\"[[app_name]]\"})"
      }
     ]
    }
   ]
  }
 ]
}