{
 "title": "Spark",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Spark spark_mesos_drivers_retry",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "spark_mesos_drivers_retry" }
   ]
  },
  {
   "title": "Spark Dispatcher jvm_heap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "spark_jvm_heap_usage", "legendFormat": "heap_usage" },
    { "expr": "spark_jvm_heap_max", "legendFormat": "heap_max" },
    { "expr": "spark_jvm_heap_used", "legendFormat": "heap_used" },
    { "expr": "spark_jvm_heap_committed", "legendFormat": "heap_committed" }
   ]
  },
  {
   "title": "Spark spark_mesos_drivers_waiting",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "spark_mesos_drivers_waiting" }
   ]
  },
  {
   "title": "Spark - Dispatcher - cpus_user_time_secs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cpus_user_time_secs{task_name=~\"spark-.*\"}"
    }
   ]
  },
  {
   "title": "spark_mesos_drivers_launched",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "spark_mesos_drivers_launched" }
   ]
  },
  {
   "title": "Spark Dispatchers - cpu_system_time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cpus_system_time_secs{task_name=~\"spark-.*\"}"
    }
   ]
  },
  {
   "title": "Spark Drivers - dagscheduler Message Processing Time p99",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_driver_dagscheduler_messageprocessingtime_p99_sum"
    }
   ]
  },
  {
   "title": "spark_mesos_cluster driver scheduling",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(spark_mesos_cluster_launcheddrivers)",
     "legendFormat": "launched"
    },
    {
     "expr": "sum(spark_mesos_drivers_waiting)",
     "legendFormat": "waiting"
    },
    { "expr": "sum(spark_mesos_drivers_retry)", "legendFormat": "retrying" }
   ]
  },
  {
   "title": "Spark Driver-Executor Active Tasks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(spark_executor_executor_threadpool_activetasks)"
    }
   ]
  },
  {
   "title": "Spark Drivers - mem_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "mem_total_bytes{task_name=~\"Driver for.*\"}"
    }
   ]
  },
  {
   "title": "Spark Drivers - jvm_total_used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "spark_jvm_total_used" }
   ]
  },
  {
   "title": "Spark Drivers - cpus_system_time_secs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cpus_system_time_secs{task_name=~\"Driver for.*\"}"
    }
   ]
  },
  {
   "title": "Spark Drivers jvm_heap_used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "jvm_memory_heap_usage" }
   ]
  },
  {
   "title": "Spark Drivers - cpus_user_time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cpus_user_time_secs{task_name=~\"Driver for.*\"}"
    }
   ]
  },
  {
   "title": "Spark Dispatcher  jvm_non_heap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "spark_jvm_heap_used" },
    { "expr": "spark_jvm_non_heap_max" },
    { "expr": "spark_jvm_non_heap_committed" },
    { "expr": "spark_jvm_non_heap_used" }
   ]
  },
  {
   "title": "Spark Dispatchers - mem_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "mem_total_bytes{task_name=~\"spark-.*\"}"
    }
   ]
  },
  {
   "title": "Spark Drivers - disk_used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "disk_used_bytes{task_name=~\"Driver for.*\"}"
    }
   ]
  },
  {
   "title": "Spark Dispatchers - disk_used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "decbytes", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "disk_used_bytes{task_name=~\"spark-.*\"}"
    }
   ]
  }
 ]
}