{
 "title": "Spark: Applications",
 "description": "Spark Dispatcher and Driver Level Metrics with filtering by service",
 "tags": [ "spark" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "origin", "label": "Origin", "query": "label_values(spark_origin)" },
   {
    "name": "app_name",
    "label": "Application Name",
    "query": "label_values(spark_driver_jvm_heap_used{spark_origin =~ \"[[origin]]\" }, spark_app_name)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Executors Running",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_mesos_executor_count{spark_origin=~\"[[origin]]\", spark_app_name=~\"[[app_name]]\"})"
    }
   ]
  },
  {
   "title": "Mesos Agents Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_mesos_occupied_agents{spark_origin=~\"[[origin]]\"}) "
    }
   ]
  },
  {
   "title": "Blacklisted Agents",
   "type": "singlestat",
   "description": "Number of blacklisted agents (too many failures)",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_mesos_blacklisted_agents{spark_origin=~\"[[origin]]\"})"
    }
   ]
  },
  {
   "title": "CPUs Used",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(spark_mesos_resource_cores{spark_origin=~\"[[origin]]\"}) by (app_name)",
     "legendFormat": "CPUs Used by Application"
    }
   ]
  },
  {
   "title": "GPUs Used",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(spark_mesos_resource_gpus{spark_origin=~\"[[origin]]\"}) by (app_name)",
     "legendFormat": "GPUs Used by Application"
    }
   ]
  },
  {
   "title": "CPUs per Task",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(spark_mesos_resource_mean_cores_per_task{spark_origin=~\"[[origin]]\"}) by (app_name)",
     "legendFormat": "GPUs Used by Application"
    }
   ]
  },
  {
   "title": "GPUs per Task",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(spark_mesos_resource_mean_gpus_per_task{spark_origin=~\"[[origin]]\"}) by (app_name)",
     "legendFormat": "GPUs Used by Application"
    }
   ]
  },
  {
   "title": "Mesos Task Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(spark_mesos_mesos_state_task_running{spark_origin=~\"[[origin]]\", spark_app_name=~\"[[app_name]]\"})",
     "legendFormat": "dropped"
    },
    {
     "expr": "sum(spark_mesos_mesos_state_task_finished{spark_origin=~\"[[origin]]\", spark_app_name=~\"[[app_name]]\"})"
    },
    {
     "expr": "sum(spark_mesos_mesos_state_task_failed{spark_origin=~\"[[origin]]\", spark_app_name=~\"[[app_name]]\"})"
    },
    {
     "expr": "sum(spark_mesos_mesos_state_task_error{spark_origin=~\"[[origin]]\", spark_app_name=~\"[[app_name]]\"})"
    },
    {
     "expr": "sum(spark_mesos_mesos_state_task_killed{spark_origin=~\"[[origin]]\", spark_app_name=~\"[[app_name]]\"})"
    },
    {
     "expr": "sum(spark_mesos_mesos_state_task_lost{spark_origin=~\"[[origin]]\", spark_app_name=~\"[[app_name]]\"})"
    },
    {
     "expr": "sum(spark_mesos_mesos_state_task_dropped{spark_origin=~\"[[origin]]\", spark_app_name=~\"[[app_name]]\"})"
    },
    {
     "expr": "sum(spark_mesos_mesos_state_task_gone{spark_origin=~\"[[origin]]\", spark_app_name=~\"[[app_name]]\"})"
    },
    {
     "expr": "sum(spark_mesos_mesos_state_task_unreachable{spark_origin=~\"[[origin]]\", spark_app_name=~\"[[app_name]]\"})"
    },
    {
     "expr": "sum(spark_mesos_mesos_state_task_unknown{spark_origin=~\"[[origin]]\", spark_app_name=~\"[[app_name]]\"})"
    }
   ]
  },
  { "title": "Execution Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Driver Heap (max/used)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(spark_driver_jvm_total_max{spark_origin=~\"[[origin]]\"}) by (app_name)",
     "legendFormat": "Heap max"
    },
    {
     "expr": "max(spark_driver_jvm_total_used{spark_origin=~\"[[origin]]\"}) by (app_name)",
     "legendFormat": "Heap used"
    }
   ]
  },
  {
   "title": "Executor Heap (max/used)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(spark_executor_jvm_total_max{spark_origin=~\"[[origin]]\"}) by (app_name)",
     "legendFormat": "Heap max"
    },
    {
     "expr": "max(spark_executor_jvm_total_used{spark_origin=~\"[[origin]]\"}) by (app_name)",
     "legendFormat": "Heap used"
    }
   ]
  },
  {
   "title": "BlockManager (on-heap memory)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_driver_blockmanager_memory_maxonheapmem_mb{spark_origin=~\"[[origin]]\",spark_app_name=~\"[[app_name]]\"}",
     "legendFormat": "Max On-Heap Memory"
    },
    {
     "expr": "spark_driver_blockmanager_memory_onheapmemused_mb{spark_origin=~\"[[origin]]\",spark_app_name=~\"[[app_name]]\"}",
     "legendFormat": "On-Heap Memory Used"
    }
   ]
  },
  {
   "title": "BlockManager (off-heap memory)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_driver_blockmanager_memory_maxoffheapmem_mb{spark_origin=~\"[[origin]]\",spark_app_name=~\"[[app_name]]\"}",
     "legendFormat": "Max Off-Heap Memory"
    },
    {
     "expr": "spark_driver_blockmanager_memory_offheapmemused_mb{spark_origin=~\"[[origin]]\",spark_app_name=~\"[[app_name]]\"}",
     "legendFormat": "Off-Heap Memory Used"
    }
   ]
  },
  {
   "title": "BlockManager (disk)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_driver_blockmanager_disk_diskspaceused_mb{spark_origin=~\"[[origin]]\",spark_app_name=~\"[[app_name]]\"}",
     "legendFormat": "Disk Space Used"
    }
   ]
  },
  { "title": "DAG Scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_driver_dagscheduler_job_alljobs",
     "legendFormat": "All Jobs"
    },
    {
     "expr": "spark_driver_dagscheduler_job_activejobs",
     "legendFormat": "Active Jobs"
    }
   ]
  },
  {
   "title": "Stages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_driver_dagscheduler_stage_runningstages",
     "legendFormat": "Running Stages"
    },
    {
     "expr": "spark_driver_dagscheduler_stage_waitingstages",
     "legendFormat": "Waiting Stages"
    },
    {
     "expr": "spark_driver_dagscheduler_stage_failedstages",
     "legendFormat": "Failed Stages"
    }
   ]
  }
 ]
}