{
 "title": "Spark: Jobs Summary",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Allocated vs Guarantee Dispatcher-0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesos_allocator_quota_roles_resources_offered_or_allocated{resource=\"cpus\", role=\"dispatcher-mixed-0-dispatcher-role\"}"
    },
    {
     "expr": "mesos_allocator_quota_roles_resources_limit{resource=\"cpus\", role=\"dispatcher-mixed-0-dispatcher-role\"}"
    },
    {}
   ]
  },
  {
   "title": "Allocated vs Guaranteed CPU all agents",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesos_allocator_quota_roles_resources_offered_or_allocated{resource=\"cpus\"}"
    },
    {
     "expr": "mesos_allocator_quota_roles_resources_limit{resource=\"cpus\"}"
    }
   ]
  },
  {
   "title": "Number of Dispatchers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_mesos_drivers_launched_count"
    }
   ]
  },
  {
   "title": "Number of Jobs Running",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(spark_mesos_executor_count)"
    }
   ]
  },
  {
   "title": "Number of Jobs by App Name",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(spark_mesos_executor_count{task_name=~\".*Kafka.*\"})",
     "legendFormat": "Spark-Streaming Kafka"
    },
    {
     "expr": "count(spark_mesos_executor_count{task_name=~\".*monte.*\"})",
     "legendFormat": "Monte-Carlo batch"
    },
    {
     "expr": "count(spark_mesos_executor_count{task_name=~\".*image.*\"})",
     "legendFormat": "Image-Recognition GPU"
    }
   ]
  },
  {
   "title": "Number of Drivers Reporting Metrics vs. Jobs Reported by Dispatchers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(spark_mesos_executor_count)",
     "legendFormat": "Number of drivers reporting"
    },
    {
     "expr": "spark_mesos_drivers_launched_count",
     "legendFormat": "Number of jobs reported by dispatchers"
    }
   ]
  },
  {
   "title": "Avg. Queue Depth per Dispatcher",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(spark_mesos_drivers_waiting)"
    }
   ]
  },
  {
   "title": "Avg. Number of Jobs per Dispatcher",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(spark_mesos_drivers_launched)"
    }
   ]
  },
  {
   "title": "Avg. Number of Executors per Job",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(spark_mesos_executor_count)"
    }
   ]
  },
  {
   "title": "Avg. Job Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(spark_mesos_drivers_launch_to_finish_state_finished_mean_mean) / 60000"
    }
   ]
  },
  {
   "title": "Job Success Rate",
   "type": "graph",
   "description": "% of jobs that finish successfully",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(spark_mesos_drivers_finished_count_mesos_state_task_finished) / (sum(spark_mesos_drivers_finished_count_mesos_state_task_finished) + sum(spark_mesos_drivers_finished_count_mesos_state_task_lost) + sum(spark_mesos_drivers_finished_count_mesos_state_task_failed))"
    }
   ]
  },
  {
   "title": "Avg. Job Launch Latency",
   "type": "graph",
   "description": "The average of how long it takes for a Spark driver to launch all its executors",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short", "label": "Time (sec)" }
   ],
   "targets": [
    {
     "expr": "avg(spark_mesos_start_to_all_launched_mean_mean) / 1000"
    }
   ]
  },
  {
   "title": "Avg. Number of Queued Retry Jobs per Dispatcher",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(spark_mesos_drivers_retry)" }
   ]
  },
  {
   "title": "Job Launch Time Std. Dev. (sec.)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stddev(spark_mesos_start_to_all_launched_mean_mean) / 1000"
    }
   ]
  }
 ]
}