{
 "title": "Streaming test SLOs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Ingress traffic of least loaded kafka cluster",
   "type": "graph",
   "description": "Must be above 1Gbps (green zone) in steady state, and above 650Mbps during fault injection (warning zone).\n\nNote that this omits built-in topics (whose name starts with underscore).",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "min(sum(kafka_server_brokertopicmetrics_bytesinpersec_1minuterate{topic!~\"_.*\"}) by (framework_id)) * 8"
    }
   ]
  },
  {
   "title": "Egress traffic of least loaded kafka cluster",
   "type": "graph",
   "description": "Must be above 10Gbps (green zone) in steady state, and above 6.5Gbps during fault injection (warning zone).\n\nNote that this omits built-in topics (whose name starts with underscore).",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "min(sum(kafka_server_brokertopicmetrics_bytesoutpersec_1minuterate{topic!~\"_.*\"}) by (framework_id)) * 8"
    }
   ]
  },
  {
   "title": "Consumer lag",
   "type": "graph",
   "description": "Consumer lag in seconds, at 99th percentile. Must not exceed 10 seconds.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "quantile(0.99,kafka_consumer_fetch_manager_metrics_records_lag_max{task_name!~\"Driver.*\"}) / max(kafka_server_brokertopicmetrics_messagesinpersec_1minuterate{topic!~\"_.*\"})",
     "legendFormat": "99th %-ile lag"
    }
   ]
  },
  {
   "title": "Number of Healthy Kafka Clusters (by Broker State)",
   "type": "graph",
   "description": "Shows the number of kafka clusters which have all 5 or brokers in state 3 (running as broker).\n\nIn steady state, the line for 5 brokers must be equal to 25. During fault injection, the line for \"4 or 5 brokers\" must be equal to 25.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(kafka_server_kafkaserver_brokerstate == bool 3) by (framework_id) == bool 5)",
     "legendFormat": "5 brokers"
    },
    {
     "expr": "sum(sum(kafka_server_kafkaserver_brokerstate == bool 3) by (framework_id) >= bool 4)",
     "legendFormat": "4 or 5 brokers"
    }
   ]
  },
  {
   "title": "Number of clusters with N healthy brokers (by request traffic)",
   "type": "graph",
   "description": "Here a broker is considered healthy if its request rate differs from median request rate for all brokers in a cluster by no more than 40%.\n\nIn steady state, the line for 5 healthy brokers should equal 25. During fault injection it can go down and the line for 4 healthy brokers can go up to 25, but no other line should change from 0.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_values(\"healthy brokers\", count(abs(kafka_socket_server_metrics_request_rate / on(framework_id) group_left(index) (quantile(0.5, kafka_socket_server_metrics_request_rate) by (framework_id)) - 1) < 0.4) by (framework_id))"
    }
   ]
  },
  {
   "title": "Healthy ZooKeeper Ensembles",
   "type": "graph",
   "description": "Number of zookeeper ensembles which have at least N healthy nodes (where a  node is considered healthy if it has at least one alive connection).\n\nLine for at least 5 healthy nodes should be equal to 25 except maybe during failure injection.\n\nLine for at least 4 healthy nodes should be equal to 25 at all times.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count(zk_num_alive_connections > 0) by (framework_id) >= bool 5)",
     "legendFormat": "At least 5 healthy nodes"
    },
    {
     "expr": "sum(count(zk_num_alive_connections > 0) by (framework_id) >= bool 4)",
     "legendFormat": "At least 4 healthy nodes"
    }
   ]
  },
  {
   "title": "Kafka and Zookeeper scheduler health",
   "type": "graph",
   "description": "Shows number of healthy kafka and zookeeper schedulers. Should equal 25 for each, except maybe during fault injection.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count(offers_processed{task_name=~\".*zookeeper-[0-9][0-9].*\"}) by (task_name) == bool 1)",
     "legendFormat": "Zookeeper"
    },
    {
     "expr": "sum(count(offers_processed{task_name=~\".*kafka-[0-9][0-9].*\"}) by (task_name) == bool 1)  ",
     "legendFormat": "Kafka"
    }
   ]
  }
 ]
}