#!/bin/sh
set -e
set -x

exec 2>&1

export APPLICATION_WEB_PROXY_BASE="${DISPATCHER_UI_WEB_PROXY_BASE}"

cd /opt/spark/dist

sed "s,<WEBUI_URL>,${WEBUI_URL},;s,<HISTORY_SERVER_URL>,${HISTORY_SERVER_WEB_PROXY_BASE}," \
    conf/mesos-cluster-dispatcher.properties.template >conf/mesos-cluster-dispatcher.properties

exec /opt/spark/dist/bin/spark-class \
    org.apache.spark.deploy.mesos.MesosClusterDispatcher \
    --port "${DISPATCHER_PORT}" \
    --webui-port "${DISPATCHER_UI_PORT}" \
    --master "${MESOS_MASTER}" \
    --zk "${ZK}" \
    --host "${HOST}" \
    --name "${FRAMEWORK_NAME}" \
    --properties-file "conf/mesos-cluster-dispatcher.properties"

